import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv(r"C:\Users\nandi\OneDrive\Desktop\oasis\TASK1\retail_sales_dataset.csv")
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)
print("Basic Statistics:")
print(data[['Transaction ID', 'Age', 'Quantity', 'Price per Unit', 'Total Amount']].describe())
print("\nMode:")
print(data.mode().iloc[0])
monthly_sales = data.resample('ME').sum()  
print("\nMonthly Sales Trend:")
print(monthly_sales[['Total Amount']])
print("\nCustomer Age Distribution:")
print(data['Age'].describe())
print("\nProduct Analysis (Quantity Distribution):")
print(data['Quantity'].describe())
plt.figure(figsize=(12, 10))
plt.subplot(2, 2, 1)
monthly_sales['Total Amount'].plot(kind='line', title='Monthly Sales Trend')
plt.ylabel('Total Amount')
plt.subplot(2, 2, 2)
data['Quantity'].plot(kind='hist', bins=20, title='Quantity Distribution')
plt.xlabel('Quantity')
plt.subplot(2, 2, 3)
data['Age'].plot(kind='hist', bins=20, title='Age Distribution')
plt.xlabel('Age')
plt.subplot(2, 2, 4)
sns.heatmap(data[['Age', 'Quantity', 'Price per Unit', 'Total Amount']].corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, linecolor='black')
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()
print("\nRecommendations Based on EDA:")
print("1. Focus marketing efforts on customers with higher average purchase amounts.")
print("2. Optimize inventory based on the most frequently purchased products.")
print("3. Consider promotional campaigns targeting specific age groups based on sales patterns.")
